### ISSUE TITLE
关于预测结果

### ISSUE THREAD

**Issue by Zakeiswo** [yuhuan-wu/MobileSal#2]
请问有NJU2K（500张）的结果图吗。现在NJU2K是485张的。

**Comment by yuhuan-wu** [comment]
Dear reader, NJU2K has 1985 images.  We follow other popular papers to use 1500 NJU2K images for training and the other 485 images for testing. **So there are not 500 NJU2K images in the test set.** 
For more details, please refer to our MobileSal paper. Thank you!
